### ISSUE TITLE
New Feature: maintain Net latency histograms per ISP

### ISSUE THREAD

**Issue by bizzbyster** [RebelBrowser/rebel#25]
It would be great to see statistics on the real end-to-end latency of different ISP networks so that histograms like DNS (DNS_Resolution_And_TCP_Connection_Latency2), TCP(Net.TCP_Connection_Latency), and SSL (SSL_Connection_Latency_2  and see below) can be stored separately based on the ISP, which would be detected via a lookup using a site like https://www.whatismyisp.com/ whenever the [network change event](url) fires.

<img width="812" alt="image" src="https://github.com/RebelBrowser/rebel/assets/4001792/77318bb6-13c9-421b-9952-50ed2500092d">

This histogram data is uploaded via UMA and then a web site can be made to view the accumulated statistics on a per ISP basis. Also include Net.TcpConnectAttempt.Latency.Error, Net.TcpConnectAttempt.Latency.Success in the list of per ISP histograms.

Definition of done:

- [ ] Run Rebel browser and browse to a web site
- [ ] go to chrome://histograms and see each of the above mentioned histogram with the current ISP string appended to the name of each
- [ ] Chrome://flag for "per ISP network latency histogram" experimental feature that enables the feature

**Comment by abcpro1** [comment]
Hi @bizzbyster! Since you have posted a bounty on this issue at Bountysource; I would be interested in working on it, except I wonder if this feature belongs in the Rebel browser. Is the Rebel browser team interested in maintaining it in the long term? What happens if I rush to make a pull request and it never gets accepted?

**Comment by bizzbyster** [comment]
@abcpro1 thanks for responding. I have spoken to the owner of the Rebel fork (@trflynn89) and he says he will accept the pull request. Sound good?

**Comment by abcpro1** [comment]
@bizzbyster OK! I'll start working on it in the next few days. I'll keep you updated.

**Comment by abcpro1** [comment]
Thanks for the hint. I'll check it out.

**Comment by bizzbyster** [comment]
Hi @abcpro1 how is it going? If possible, it would be awesome to also add this histogram to those that are recorded on a per ISP basis:
<img width="1231" alt="image" src="https://github.com/RebelBrowser/rebel/assets/4001792/6ee49e61-dff0-4208-a3d7-0f42c0352daa">

**Comment by abcpro1** [comment]
@bizzbyster It doesn't seem hard to segregate histograms by some criteria like ISP. But it doesn't look like the NETWORK_CHANGE event monitors IP address changes. What I will probably do is check periodically (maybe once a minute) the current ISP, and once that changes trigger a custom event, then react to it accordingly.

**Comment by bizzbyster** [comment]
That is good enough. Does this help?

**Comment by abcpro1** [comment]
@bizzbyster I have some good news! Finally. Sorry for taking this long. I have pretty much completely finished. The only thing left is to make it switchable with a flag. So, expect a pull request within a day from now.

**Comment by bizzbyster** [comment]
Fantastic!

**Comment by abcpro1** [comment]
@bizzbyster The pull request is ready at #26.

**Comment by bizzbyster** [comment]
@trflynn89
Can we get this reviewed and tested please?

**Comment by bizzbyster** [comment]
@trflynn89
any update? @abcpro1 has been waiting a while.

**Comment by nachocardozop** [comment]
Hi @abcpro1, in order for me to send you the payment over Bountysource I think you will need to commit to the issue within the platform. Can you please try to do that and let me know?

I think you need to click "solve" and follow the flow here:
https://app.bountysource.com/issues/123114374-new-feature-maintain-net-latency-histograms-per-isp

**Comment by abcpro1** [comment]
@nachocardozop OK. I have just submitted a claim in Bountysource.

**Comment by bizzbyster** [comment]
Great work!! Message me if you are interested in developing more cool features like this.

**Comment by nachocardozop** [comment]
Awesome, just approved it @abcpro1
